/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as HackathonsIndexRouteImport } from './routes/hackathons.index'
import { Route as HackathonsSlugRouteImport } from './routes/hackathons.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIndexRoute = HackathonsIndexRouteImport.update({
  id: '/hackathons/',
  path: '/hackathons/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsSlugRoute = HackathonsSlugRouteImport.update({
  id: '/hackathons/$slug',
  path: '/hackathons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/hackathons/': typeof HackathonsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/hackathons': typeof HackathonsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/hackathons/': typeof HackathonsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery'
    | '/competitions/$slug'
    | '/hackathons/$slug'
    | '/projects/$slug'
    | '/competitions/'
    | '/hackathons/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/competitions/$slug'
    | '/hackathons/$slug'
    | '/projects/$slug'
    | '/competitions'
    | '/hackathons'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery'
    | '/competitions/$slug'
    | '/hackathons/$slug'
    | '/projects/$slug'
    | '/competitions/'
    | '/hackathons/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRoute
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  HackathonsSlugRoute: typeof HackathonsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  HackathonsIndexRoute: typeof HackathonsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/': {
      id: '/hackathons/'
      path: '/hackathons'
      fullPath: '/hackathons/'
      preLoaderRoute: typeof HackathonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$slug': {
      id: '/hackathons/$slug'
      path: '/hackathons/$slug'
      fullPath: '/hackathons/$slug'
      preLoaderRoute: typeof HackathonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRoute,
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  HackathonsSlugRoute: HackathonsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  HackathonsIndexRoute: HackathonsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
